# Create the conda environment with the following statement:
# conda env create -f environment.yml
name: pydata
channels:
  - conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib=3.7
  - notebook
  - numpy=1.23
  - python=3.10
  - scipy=1.10
